feat: add `MSSQLChatMessageHistory` class
googleapis/langchain-google-cloud-sql-mssql-python pull request #9
Opened 2024-02-05 13:45 UTC by jackwotherspoon

Add Cloud SQL for SQL Server `MSSQLChatMessageHistory` class to enable a memory store.

Follows pattern of other chat message history integrations: https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community/chat_message_histories

This is a port of https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/pull/13

2024-02-05 16:52 UTC, kurtisvg requested changes

2024-02-05 16:52 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
I'm hesitant about creating tables automatically -- it seems like we should be consistent w/ vectorstore and make the user create the table before the object initialization

2024-02-05 16:52 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def messages(self) -> List[BaseMessage]:  # type: ignore
Why is this type ignore?

2024-02-05 16:52 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +        ]
nit: I think you can one-line this
```suggestion
        items = [ {"data": json.loads(r[0]), "type": r[1]} for r in results ]
```

2024-02-05 18:20 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +        ]
I did have it as one line but this is how `black` is formatting it 🤷‍♂️

2024-02-05 18:21 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +        ]
I see you made results var smaller, will update

2024-02-05 18:25 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
> I'm hesitant about creating tables automatically

How come? Just because users may not know it is happening under the hood and to make it more explicit?

> make the user create the table before the object initialization

@kurtisvg like have this as a public method that the user needs to explicitly call?

2024-02-05 18:28 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def messages(self) -> List[BaseMessage]:  # type: ignore
otherwise mypy throws an error to do with Langchain base class...
```
src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py:55: error: Cannot override writeable attribute with read-only property  [override]
```

This type ignore is being done by all current integrations: [MongoDB ChatMessageHistory](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/mongodb.py#L53)

2024-02-05 18:35 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
@averikitsch for thoughts

I guess my concern is that we are creating a table somewhat implicitly, which means typos would lead to a new table instead of an error. I would rather have provisioning of a new resource (table) be more explicit.

2024-02-05 18:42 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
It seems like it is common for `ChatMessageHistory` integrations to create the table automatically for the user:
- [SQLAlchemy ORM integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/sql.py#L101)
- [Postgres Integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/postgres.py#L38)
- [RocksetDB Integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/rocksetdb.py#L67)
- [DynamoDB Integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/dynamodb.py#L98)
- [AstraDB Integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/astradb.py#L58)

Thoughts on following the pattern that other integrations use and keeping the auto creation of table?

2024-02-05 18:46 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
I doubt most users will even set `table_name` which reduces potential for typos drastically as it seems most other integrations default table name to `message_store` (as we do here) so that users just expect `ChatMessageHistory` to create/use a table called `message_store`

2024-02-06 15:50 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
I don't like that we're using a default table name either :)

2024-02-06 19:59 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
@kurtisvg  Sounds good I'm open to suggestions, was just following the other integrations for the most part. Happy to change it for whatever we decide on. Otherwise this is just a port of MySQL PR.

2024-02-06 20:08 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +    def _create_table_if_not_exists(self) -> None:
Averi, Tabby, and I discussed at length yesterday and landed on:

- Ask the user to initialize before object is init'd
- Object should verify the schema when it is init'd (and error otherwise)
- make table name a required arg

I know this goes against some of the other integrations, but is consistent with how we are doing VectorStore/DocLoader/Saver.

2024-02-08 00:10 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_engine.py
> +            WHERE TABLE_NAME = '{table_name}')
I left the `IF NOT EXISTS` here still as I feel like this is less error prone. Most likely these integrations will be run in scripts/notebooks or ran multiple times. We want methods to be able to be run more than once and not error out.

2024-02-08 18:44 UTC, kurtisvg approved these changes

2024-02-08 18:44 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +        Required schema is as follows:
nit: IDK how much value there in documenting the schema -- but maybe add they should use the schema creation function we created

2024-02-08 18:44 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mssql/mssql_engine.py
> +            WHERE TABLE_NAME = '{table_name}')
nit: I'm a little concerned by this because it seems like the table might exist but have the wrong schema. Can we throw an error if it's the wrong schema?

2024-02-08 18:54 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_engine.py
> +            WHERE TABLE_NAME = '{table_name}')
Discussed offline and if table already exists with malformed schema it will error with a nice error when user attempts to init `MSSQLChatMessageHistory`

2024-02-08 18:59 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mssql/mssql_chat_message_history.py
> +        Required schema is as follows:
Updated docstring to recommend using helper method for valid schema

2024-02-08 18:59 UTC, merged